In [ ]:
# Check to see if table was created
import sqlite3
import os
os.chdir('c:\\Projects\\SQL_NOSQL')

# Question 1
conn = sqlite3.connect('ABC_corp.db')  # <== create the database
c = conn.cursor()
for row in c.execute("""SELECT name FROM sqlite_master"""):
    print(row)
c.executescript('''
    create table IF NOT EXISTS employees(
        emp_id TEXT,
        first_name TEXT,
        last_name TEXT,
        middle_name TEXT,
        gender_code TEXT,
        pronouns TEXT,
        marital_status_code TEXT,
        doh TEXT,
        supervisor_id TEXT,
        term_date TEXT,
        term_code TEXT,
        dept_code TEXT,
        max_sick_days INTEGER
    );
    create table IF NOT EXISTS marital_status(
        code TEXT,
        description TEXT
    );
    create table IF NOT EXISTS depts(
        code TEXT,
        description TEXT
    );
    create table IF NOT EXISTS term_reason(
        code TEXT,
        description TEXT
    );
    create table IF NOT EXISTS sick_days(
        code TEXT,
        description TEXT
    );
    create table IF NOT EXISTS sales(
        code TEXT,
        description TEXT
    );
    create table IF NOT EXISTS out_reason(
        code TEXT,
        description TEXT
    );
    ''')
conn.commit()
# list all of the tables
for row in c.execute("""SELECT name FROM sqlite_master"""):
    print(row)
conn.close()

In [ ]:
import sqlite3
import os
cwd = os.getcwd()
# print(cwd)
os.chdir(r'/Users/julis_478/Documents/Python Immersives/PY-112 SQL, No SQL/Classes/Day6')
cwd = os.getcwd()
# print(cwd)
# Question 1
conn = sqlite3.connect('ABC_corp.db')  # <== create the database
c = conn.cursor()
for row in c.execute("""SELECT name FROM sqlite_master"""):
    print(row)
c.executescript('''
    create table IF NOT EXISTS employees(
        emp_id TEXT,
        first_name TEXT,
        last_name TEXT,
        middle_name TEXT,
        gender_code TEXT,
        pronouns TEXT,
        marital_status_code TEXT,
        doh TEXT,
        supervisor_id TEXT,
        term_date TEXT,
        term_code TEXT,
        dept_code TEXT,
        max_sick_days INTEGER
    );
    create table IF NOT EXISTS marital_status(
        code TEXT,
        description TEXT
    );
    create table IF NOT EXISTS depts(
        code TEXT,
        description TEXT
    );
    create table IF NOT EXISTS term_reason(
        code TEXT,
        description TEXT
    );
    create table IF NOT EXISTS sick_days(
        code TEXT,
        description TEXT
    );
    create table IF NOT EXISTS sales(
        code TEXT,
        description TEXT
    );
    create table IF NOT EXISTS out_reason(
        code TEXT,
        description TEXT
    );
    ''')
conn.commit()
# list all of the tables
for row in c.execute("""SELECT name FROM sqlite_master"""):
    print(row)
conn.close()

In [27]:
import sqlite3
import os
cwd = os.getcwd()
os.chdir(r'/Users/julis_478/Documents/Python Immersives/PY-112 SQL, No SQL/Classes/Day6')
cwd = os.getcwd()
conn = sqlite3.connect('ABC_corp.db')  # <== create the database
c = conn.cursor()

with open('ABC_CORP_DATA.csv','r') as myFile:

    # 1 - Add the data to a data structure
    headLine = myFile.readline()
    content = myFile.readlines()
    # print(content[0])
    # print(type(content[0]))
    for presd in (content):
        # Clean the data
        line_elements = presd.split(',')
        # print(line_elements[0],line_elements[1],line_elements[2])
        # print(line_elements[:13])
        c.execute('''INSERT   INTO employees
                VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)''',line_elements[:13])
        conn.commit()
    print('='*35)
    # Retreive all table names in the database
    for row in c.execute("""SELECT name FROM sqlite_master"""):
        print(row)
    print('='*35)
    for row in conn.execute("""SELECT  * FROM employees"""):
        print(row)

===================================
('employees',)
('marital_status',)
('depts',)
('term_reason',)
('sick_days',)
('sales',)
('out_reason',)
===================================
('EE-001', 'George', 'Deeds', 'Oscar', 'Male', '', 'Married', '2/12/2011', '', '', '', 'Finance', 5)
('EE-002', 'Mary', 'Wells', 'Virginia', 'Female', '', 'Married', '3/10/2015', 'EE-001', '5/12/2019', 'Quit', 'Finance', 5)
('EE-003', 'Donald', 'Wright', '', 'Male', '', 'Divorced', '8/1/2014', 'EE-001', '6/20/2020', 'Fired', 'Back Office', 5)
('EE-004', 'Shiela', 'Soros', 'Olivia', 'Female', '', 'Married', '2/12/2017', 'EE-007', '8/9/2020', 'Died', 'Accounting', 5)
('EE-005', 'Samuel', 'Rickets', 'Axel', 'Male', '', 'Single', '12/6/2017', 'EE-001', '', '', 'Finance', 5)
('EE-006', 'April', 'Walters', 'Amanda', 'Female', '', 'Married', '11/4/2015', 'EE-001', '', '', 'Finance', 5)
('EE-007', 'Avi', 'Feldman', '', 'Male', '', 'Single', '6/13/2016', 'EE-001', '', '', 'Accounting', 5)
('EE-008', 'Lea', 'Goldman', 'Elisa', 'Female', '', 'Single', '7/18/2019', 'EE-005', '', '', 'Finance', 5)
('EE-009', 'Henry', 'Williams', 'Robert', 'Male', '', 'Widowed', '10/5/2017', 'EE-005', '', '', 'Finance', 5)
('EE-010', 'Lois', 'Engels', '', 'Female', '', 'Single', '3/18/2010', 'EE-001', '', '', 'Human Resources', 5)
('EE-011', 'Fredrick', 'Rome', 'Aaron', 'Male', '', 'Single', '8/1/2018', 'EE-010', '', '', 'Human Resources', 5)
('EE-012', 'Regina', 'Polk', 'Ann', 'Female', '', 'Single', '12/10/2018', 'EE-010', '', '', 'Human Resources', 5)
('EE-013', 'Sara', 'Silver', 'Omara', 'Female', '', 'Single', '4/16/2016', 'EE-007', '', '', 'Accounting', 5)
('EE-014', 'Donald', 'Friar', 'Paul', 'Male', '', 'Single', '2/25/2017', 'EE-007', '', '', 'Accounting', 5)
('EE-015', 'Wendy', 'Rose', '', 'Female', '', 'Married', '5/17/2016', 'EE-017', '', '', 'Sales', 5)
('EE-016', 'Quentin', 'Paul', '', 'Male', '', 'Married', '5/18/2018', 'EE-017', '', '', 'Sales', 5)
('EE-017', 'Felicia', 'Kellogg', 'Paula', 'Female', '', 'Divorced', '5/19/2018', 'EE-001', '', '', 'Sales', 5)
('EE-018', 'Barbra', 'Banton', 'Betty', 'Female', '', 'Single', '5/20/2018', 'EE-017', '', '', 'Sales', 5)
('EE-019', 'Saul', 'Denosen', 'Peter', 'Male', '', 'Single', '5/21/2018', 'EE-017', '', '', 'Sales', 5)
('EE-020', 'Leon', 'Williams', '', 'Male', '', 'Single', '5/22/2018', 'EE-017', '', '', 'Sales', 5)
('EE-001', 'George', 'Deeds', 'Oscar', 'Male', '', 'Married', '2/12/2011', '', '', '', 'Finance', 5)
('EE-002', 'Mary', 'Wells', 'Virginia', 'Female', '', 'Married', '3/10/2015', 'EE-001', '5/12/2019', 'Quit', 'Finance', 5)
('EE-003', 'Donald', 'Wright', '', 'Male', '', 'Divorced', '8/1/2014', 'EE-001', '6/20/2020', 'Fired', 'Back Office', 5)
('EE-004', 'Shiela', 'Soros', 'Olivia', 'Female', '', 'Married', '2/12/2017', 'EE-007', '8/9/2020', 'Died', 'Accounting', 5)
('EE-005', 'Samuel', 'Rickets', 'Axel', 'Male', '', 'Single', '12/6/2017', 'EE-001', '', '', 'Finance', 5)
('EE-006', 'April', 'Walters', 'Amanda', 'Female', '', 'Married', '11/4/2015', 'EE-001', '', '', 'Finance', 5)
('EE-007', 'Avi', 'Feldman', '', 'Male', '', 'Single', '6/13/2016', 'EE-001', '', '', 'Accounting', 5)
('EE-008', 'Lea', 'Goldman', 'Elisa', 'Female', '', 'Single', '7/18/2019', 'EE-005', '', '', 'Finance', 5)
('EE-009', 'Henry', 'Williams', 'Robert', 'Male', '', 'Widowed', '10/5/2017', 'EE-005', '', '', 'Finance', 5)
('EE-010', 'Lois', 'Engels', '', 'Female', '', 'Single', '3/18/2010', 'EE-001', '', '', 'Human Resources', 5)
('EE-011', 'Fredrick', 'Rome', 'Aaron', 'Male', '', 'Single', '8/1/2018', 'EE-010', '', '', 'Human Resources', 5)
('EE-012', 'Regina', 'Polk', 'Ann', 'Female', '', 'Single', '12/10/2018', 'EE-010', '', '', 'Human Resources', 5)
('EE-013', 'Sara', 'Silver', 'Omara', 'Female', '', 'Single', '4/16/2016', 'EE-007', '', '', 'Accounting', 5)
('EE-014', 'Donald', 'Friar', 'Paul', 'Male', '', 'Single', '2/25/2017', 'EE-007', '', '', 'Accounting', 5)
('EE-015', 'Wendy', 'Rose', '', 'Female', '', 'Married', '5/17/2016', 'EE-017', '', '', 'Sales', 5)
('EE-016', 'Quentin', 'Paul', '', 'Male', '', 'Married', '5/18/2018', 'EE-017', '', '', 'Sales', 5)
('EE-017', 'Felicia', 'Kellogg', 'Paula', 'Female', '', 'Divorced', '5/19/2018', 'EE-001', '', '', 'Sales', 5)
('EE-018', 'Barbra', 'Banton', 'Betty', 'Female', '', 'Single', '5/20/2018', 'EE-017', '', '', 'Sales', 5)
('EE-019', 'Saul', 'Denosen', 'Peter', 'Male', '', 'Single', '5/21/2018', 'EE-017', '', '', 'Sales', 5)
('EE-020', 'Leon', 'Williams', '', 'Male', '', 'Single', '5/22/2018', 'EE-017', '', '', 'Sales', 5)
('EE-001', 'George', 'Deeds', 'Oscar', 'Male', '', 'Married', '2/12/2011', '', '', '', 'Finance', 5)
('EE-002', 'Mary', 'Wells', 'Virginia', 'Female', '', 'Married', '3/10/2015', 'EE-001', '5/12/2019', 'Quit', 'Finance', 5)
('EE-003', 'Donald', 'Wright', '', 'Male', '', 'Divorced', '8/1/2014', 'EE-001', '6/20/2020', 'Fired', 'Back Office', 5)
('EE-004', 'Shiela', 'Soros', 'Olivia', 'Female', '', 'Married', '2/12/2017', 'EE-007', '8/9/2020', 'Died', 'Accounting', 5)
('EE-005', 'Samuel', 'Rickets', 'Axel', 'Male', '', 'Single', '12/6/2017', 'EE-001', '', '', 'Finance', 5)
('EE-006', 'April', 'Walters', 'Amanda', 'Female', '', 'Married', '11/4/2015', 'EE-001', '', '', 'Finance', 5)
('EE-007', 'Avi', 'Feldman', '', 'Male', '', 'Single', '6/13/2016', 'EE-001', '', '', 'Accounting', 5)
('EE-008', 'Lea', 'Goldman', 'Elisa', 'Female', '', 'Single', '7/18/2019', 'EE-005', '', '', 'Finance', 5)
('EE-009', 'Henry', 'Williams', 'Robert', 'Male', '', 'Widowed', '10/5/2017', 'EE-005', '', '', 'Finance', 5)
('EE-010', 'Lois', 'Engels', '', 'Female', '', 'Single', '3/18/2010', 'EE-001', '', '', 'Human Resources', 5)
('EE-011', 'Fredrick', 'Rome', 'Aaron', 'Male', '', 'Single', '8/1/2018', 'EE-010', '', '', 'Human Resources', 5)
('EE-012', 'Regina', 'Polk', 'Ann', 'Female', '', 'Single', '12/10/2018', 'EE-010', '', '', 'Human Resources', 5)
('EE-013', 'Sara', 'Silver', 'Omara', 'Female', '', 'Single', '4/16/2016', 'EE-007', '', '', 'Accounting', 5)
('EE-014', 'Donald', 'Friar', 'Paul', 'Male', '', 'Single', '2/25/2017', 'EE-007', '', '', 'Accounting', 5)
('EE-015', 'Wendy', 'Rose', '', 'Female', '', 'Married', '5/17/2016', 'EE-017', '', '', 'Sales', 5)
('EE-016', 'Quentin', 'Paul', '', 'Male', '', 'Married', '5/18/2018', 'EE-017', '', '', 'Sales', 5)
('EE-017', 'Felicia', 'Kellogg', 'Paula', 'Female', '', 'Divorced', '5/19/2018', 'EE-001', '', '', 'Sales', 5)
('EE-018', 'Barbra', 'Banton', 'Betty', 'Female', '', 'Single', '5/20/2018', 'EE-017', '', '', 'Sales', 5)
('EE-019', 'Saul', 'Denosen', 'Peter', 'Male', '', 'Single', '5/21/2018', 'EE-017', '', '', 'Sales', 5)
('EE-020', 'Leon', 'Williams', '', 'Male', '', 'Single', '5/22/2018', 'EE-017', '', '', 'Sales', 5)
('EE-001', 'George', 'Deeds', 'Oscar', 'Male', '', 'Married', '2/12/2011', '', '', '', 'Finance', 5)
('EE-002', 'Mary', 'Wells', 'Virginia', 'Female', '', 'Married', '3/10/2015', 'EE-001', '5/12/2019', 'Quit', 'Finance', 5)
('EE-003', 'Donald', 'Wright', '', 'Male', '', 'Divorced', '8/1/2014', 'EE-001', '6/20/2020', 'Fired', 'Back Office', 5)
('EE-004', 'Shiela', 'Soros', 'Olivia', 'Female', '', 'Married', '2/12/2017', 'EE-007', '8/9/2020', 'Died', 'Accounting', 5)
('EE-005', 'Samuel', 'Rickets', 'Axel', 'Male', '', 'Single', '12/6/2017', 'EE-001', '', '', 'Finance', 5)
('EE-006', 'April', 'Walters', 'Amanda', 'Female', '', 'Married', '11/4/2015', 'EE-001', '', '', 'Finance', 5)
('EE-007', 'Avi', 'Feldman', '', 'Male', '', 'Single', '6/13/2016', 'EE-001', '', '', 'Accounting', 5)
('EE-008', 'Lea', 'Goldman', 'Elisa', 'Female', '', 'Single', '7/18/2019', 'EE-005', '', '', 'Finance', 5)
('EE-009', 'Henry', 'Williams', 'Robert', 'Male', '', 'Widowed', '10/5/2017', 'EE-005', '', '', 'Finance', 5)
('EE-010', 'Lois', 'Engels', '', 'Female', '', 'Single', '3/18/2010', 'EE-001', '', '', 'Human Resources', 5)
('EE-011', 'Fredrick', 'Rome', 'Aaron', 'Male', '', 'Single', '8/1/2018', 'EE-010', '', '', 'Human Resources', 5)
('EE-012', 'Regina', 'Polk', 'Ann', 'Female', '', 'Single', '12/10/2018', 'EE-010', '', '', 'Human Resources', 5)
('EE-013', 'Sara', 'Silver', 'Omara', 'Female', '', 'Single', '4/16/2016', 'EE-007', '', '', 'Accounting', 5)
('EE-014', 'Donald', 'Friar', 'Paul', 'Male', '', 'Single', '2/25/2017', 'EE-007', '', '', 'Accounting', 5)
('EE-015', 'Wendy', 'Rose', '', 'Female', '', 'Married', '5/17/2016', 'EE-017', '', '', 'Sales', 5)
('EE-016', 'Quentin', 'Paul', '', 'Male', '', 'Married', '5/18/2018', 'EE-017', '', '', 'Sales', 5)
('EE-017', 'Felicia', 'Kellogg', 'Paula', 'Female', '', 'Divorced', '5/19/2018', 'EE-001', '', '', 'Sales', 5)
('EE-018', 'Barbra', 'Banton', 'Betty', 'Female', '', 'Single', '5/20/2018', 'EE-017', '', '', 'Sales', 5)
('EE-019', 'Saul', 'Denosen', 'Peter', 'Male', '', 'Single', '5/21/2018', 'EE-017', '', '', 'Sales', 5)
('EE-020', 'Leon', 'Williams', '', 'Male', '', 'Single', '5/22/2018', 'EE-017', '', '', 'Sales', 5)
('EE-001', 'George', 'Deeds', 'Oscar', 'Male', '', 'Married', '2/12/2011', '', '', '', 'Finance', 5)
('EE-002', 'Mary', 'Wells', 'Virginia', 'Female', '', 'Married', '3/10/2015', 'EE-001', '5/12/2019', 'Quit', 'Finance', 5)
('EE-003', 'Donald', 'Wright', '', 'Male', '', 'Divorced', '8/1/2014', 'EE-001', '6/20/2020', 'Fired', 'Back Office', 5)
('EE-004', 'Shiela', 'Soros', 'Olivia', 'Female', '', 'Married', '2/12/2017', 'EE-007', '8/9/2020', 'Died', 'Accounting', 5)
('EE-005', 'Samuel', 'Rickets', 'Axel', 'Male', '', 'Single', '12/6/2017', 'EE-001', '', '', 'Finance', 5)
('EE-006', 'April', 'Walters', 'Amanda', 'Female', '', 'Married', '11/4/2015', 'EE-001', '', '', 'Finance', 5)
('EE-007', 'Avi', 'Feldman', '', 'Male', '', 'Single', '6/13/2016', 'EE-001', '', '', 'Accounting', 5)
('EE-008', 'Lea', 'Goldman', 'Elisa', 'Female', '', 'Single', '7/18/2019', 'EE-005', '', '', 'Finance', 5)
('EE-009', 'Henry', 'Williams', 'Robert', 'Male', '', 'Widowed', '10/5/2017', 'EE-005', '', '', 'Finance', 5)
('EE-010', 'Lois', 'Engels', '', 'Female', '', 'Single', '3/18/2010', 'EE-001', '', '', 'Human Resources', 5)
('EE-011', 'Fredrick', 'Rome', 'Aaron', 'Male', '', 'Single', '8/1/2018', 'EE-010', '', '', 'Human Resources', 5)
('EE-012', 'Regina', 'Polk', 'Ann', 'Female', '', 'Single', '12/10/2018', 'EE-010', '', '', 'Human Resources', 5)
('EE-013', 'Sara', 'Silver', 'Omara', 'Female', '', 'Single', '4/16/2016', 'EE-007', '', '', 'Accounting', 5)
('EE-014', 'Donald', 'Friar', 'Paul', 'Male', '', 'Single', '2/25/2017', 'EE-007', '', '', 'Accounting', 5)
('EE-015', 'Wendy', 'Rose', '', 'Female', '', 'Married', '5/17/2016', 'EE-017', '', '', 'Sales', 5)
('EE-016', 'Quentin', 'Paul', '', 'Male', '', 'Married', '5/18/2018', 'EE-017', '', '', 'Sales', 5)
('EE-017', 'Felicia', 'Kellogg', 'Paula', 'Female', '', 'Divorced', '5/19/2018', 'EE-001', '', '', 'Sales', 5)
('EE-018', 'Barbra', 'Banton', 'Betty', 'Female', '', 'Single', '5/20/2018', 'EE-017', '', '', 'Sales', 5)
('EE-019', 'Saul', 'Denosen', 'Peter', 'Male', '', 'Single', '5/21/2018', 'EE-017', '', '', 'Sales', 5)
('EE-020', 'Leon', 'Williams', '', 'Male', '', 'Single', '5/22/2018', 'EE-017', '', '', 'Sales', 5)
('EE-001', 'George', 'Deeds', 'Oscar', 'Male', '', 'Married', '2/12/2011', '', '', '', 'Finance', 5)
('EE-002', 'Mary', 'Wells', 'Virginia', 'Female', '', 'Married', '3/10/2015', 'EE-001', '5/12/2019', 'Quit', 'Finance', 5)
('EE-003', 'Donald', 'Wright', '', 'Male', '', 'Divorced', '8/1/2014', 'EE-001', '6/20/2020', 'Fired', 'Back Office', 5)
('EE-004', 'Shiela', 'Soros', 'Olivia', 'Female', '', 'Married', '2/12/2017', 'EE-007', '8/9/2020', 'Died', 'Accounting', 5)
('EE-005', 'Samuel', 'Rickets', 'Axel', 'Male', '', 'Single', '12/6/2017', 'EE-001', '', '', 'Finance', 5)
('EE-006', 'April', 'Walters', 'Amanda', 'Female', '', 'Married', '11/4/2015', 'EE-001', '', '', 'Finance', 5)
('EE-007', 'Avi', 'Feldman', '', 'Male', '', 'Single', '6/13/2016', 'EE-001', '', '', 'Accounting', 5)
('EE-008', 'Lea', 'Goldman', 'Elisa', 'Female', '', 'Single', '7/18/2019', 'EE-005', '', '', 'Finance', 5)
('EE-009', 'Henry', 'Williams', 'Robert', 'Male', '', 'Widowed', '10/5/2017', 'EE-005', '', '', 'Finance', 5)
('EE-010', 'Lois', 'Engels', '', 'Female', '', 'Single', '3/18/2010', 'EE-001', '', '', 'Human Resources', 5)
('EE-011', 'Fredrick', 'Rome', 'Aaron', 'Male', '', 'Single', '8/1/2018', 'EE-010', '', '', 'Human Resources', 5)
('EE-012', 'Regina', 'Polk', 'Ann', 'Female', '', 'Single', '12/10/2018', 'EE-010', '', '', 'Human Resources', 5)
('EE-013', 'Sara', 'Silver', 'Omara', 'Female', '', 'Single', '4/16/2016', 'EE-007', '', '', 'Accounting', 5)
('EE-014', 'Donald', 'Friar', 'Paul', 'Male', '', 'Single', '2/25/2017', 'EE-007', '', '', 'Accounting', 5)
('EE-015', 'Wendy', 'Rose', '', 'Female', '', 'Married', '5/17/2016', 'EE-017', '', '', 'Sales', 5)
('EE-016', 'Quentin', 'Paul', '', 'Male', '', 'Married', '5/18/2018', 'EE-017', '', '', 'Sales', 5)
('EE-017', 'Felicia', 'Kellogg', 'Paula', 'Female', '', 'Divorced', '5/19/2018', 'EE-001', '', '', 'Sales', 5)
('EE-018', 'Barbra', 'Banton', 'Betty', 'Female', '', 'Single', '5/20/2018', 'EE-017', '', '', 'Sales', 5)
('EE-019', 'Saul', 'Denosen', 'Peter', 'Male', '', 'Single', '5/21/2018', 'EE-017', '', '', 'Sales', 5)
('EE-020', 'Leon', 'Williams', '', 'Male', '', 'Single', '5/22/2018', 'EE-017', '', '', 'Sales', 5)
('EE-001', 'George', 'Deeds', 'Oscar', 'Male', '', 'Married', '2/12/2011', '', '', '', 'Finance', 5)
('EE-002', 'Mary', 'Wells', 'Virginia', 'Female', '', 'Married', '3/10/2015', 'EE-001', '5/12/2019', 'Quit', 'Finance', 5)
('EE-003', 'Donald', 'Wright', '', 'Male', '', 'Divorced', '8/1/2014', 'EE-001', '6/20/2020', 'Fired', 'Back Office', 5)
('EE-004', 'Shiela', 'Soros', 'Olivia', 'Female', '', 'Married', '2/12/2017', 'EE-007', '8/9/2020', 'Died', 'Accounting', 5)
('EE-005', 'Samuel', 'Rickets', 'Axel', 'Male', '', 'Single', '12/6/2017', 'EE-001', '', '', 'Finance', 5)
('EE-006', 'April', 'Walters', 'Amanda', 'Female', '', 'Married', '11/4/2015', 'EE-001', '', '', 'Finance', 5)
('EE-007', 'Avi', 'Feldman', '', 'Male', '', 'Single', '6/13/2016', 'EE-001', '', '', 'Accounting', 5)
('EE-008', 'Lea', 'Goldman', 'Elisa', 'Female', '', 'Single', '7/18/2019', 'EE-005', '', '', 'Finance', 5)
('EE-009', 'Henry', 'Williams', 'Robert', 'Male', '', 'Widowed', '10/5/2017', 'EE-005', '', '', 'Finance', 5)
('EE-010', 'Lois', 'Engels', '', 'Female', '', 'Single', '3/18/2010', 'EE-001', '', '', 'Human Resources', 5)
('EE-011', 'Fredrick', 'Rome', 'Aaron', 'Male', '', 'Single', '8/1/2018', 'EE-010', '', '', 'Human Resources', 5)
('EE-012', 'Regina', 'Polk', 'Ann', 'Female', '', 'Single', '12/10/2018', 'EE-010', '', '', 'Human Resources', 5)
('EE-013', 'Sara', 'Silver', 'Omara', 'Female', '', 'Single', '4/16/2016', 'EE-007', '', '', 'Accounting', 5)
('EE-014', 'Donald', 'Friar', 'Paul', 'Male', '', 'Single', '2/25/2017', 'EE-007', '', '', 'Accounting', 5)
('EE-015', 'Wendy', 'Rose', '', 'Female', '', 'Married', '5/17/2016', 'EE-017', '', '', 'Sales', 5)
('EE-016', 'Quentin', 'Paul', '', 'Male', '', 'Married', '5/18/2018', 'EE-017', '', '', 'Sales', 5)
('EE-017', 'Felicia', 'Kellogg', 'Paula', 'Female', '', 'Divorced', '5/19/2018', 'EE-001', '', '', 'Sales', 5)
('EE-018', 'Barbra', 'Banton', 'Betty', 'Female', '', 'Single', '5/20/2018', 'EE-017', '', '', 'Sales', 5)
('EE-019', 'Saul', 'Denosen', 'Peter', 'Male', '', 'Single', '5/21/2018', 'EE-017', '', '', 'Sales', 5)
('EE-020', 'Leon', 'Williams', '', 'Male', '', 'Single', '5/22/2018', 'EE-017', '', '', 'Sales', 5)
('EE-001', 'George', 'Deeds', 'Oscar', 'Male', '', 'Married', '2/12/2011', '', '', '', 'Finance', 5)
('EE-002', 'Mary', 'Wells', 'Virginia', 'Female', '', 'Married', '3/10/2015', 'EE-001', '5/12/2019', 'Quit', 'Finance', 5)
('EE-003', 'Donald', 'Wright', '', 'Male', '', 'Divorced', '8/1/2014', 'EE-001', '6/20/2020', 'Fired', 'Back Office', 5)
('EE-004', 'Shiela', 'Soros', 'Olivia', 'Female', '', 'Married', '2/12/2017', 'EE-007', '8/9/2020', 'Died', 'Accounting', 5)
('EE-005', 'Samuel', 'Rickets', 'Axel', 'Male', '', 'Single', '12/6/2017', 'EE-001', '', '', 'Finance', 5)
('EE-006', 'April', 'Walters', 'Amanda', 'Female', '', 'Married', '11/4/2015', 'EE-001', '', '', 'Finance', 5)
('EE-007', 'Avi', 'Feldman', '', 'Male', '', 'Single', '6/13/2016', 'EE-001', '', '', 'Accounting', 5)
('EE-008', 'Lea', 'Goldman', 'Elisa', 'Female', '', 'Single', '7/18/2019', 'EE-005', '', '', 'Finance', 5)
('EE-009', 'Henry', 'Williams', 'Robert', 'Male', '', 'Widowed', '10/5/2017', 'EE-005', '', '', 'Finance', 5)
('EE-010', 'Lois', 'Engels', '', 'Female', '', 'Single', '3/18/2010', 'EE-001', '', '', 'Human Resources', 5)
('EE-011', 'Fredrick', 'Rome', 'Aaron', 'Male', '', 'Single', '8/1/2018', 'EE-010', '', '', 'Human Resources', 5)
('EE-012', 'Regina', 'Polk', 'Ann', 'Female', '', 'Single', '12/10/2018', 'EE-010', '', '', 'Human Resources', 5)
('EE-013', 'Sara', 'Silver', 'Omara', 'Female', '', 'Single', '4/16/2016', 'EE-007', '', '', 'Accounting', 5)
('EE-014', 'Donald', 'Friar', 'Paul', 'Male', '', 'Single', '2/25/2017', 'EE-007', '', '', 'Accounting', 5)
('EE-015', 'Wendy', 'Rose', '', 'Female', '', 'Married', '5/17/2016', 'EE-017', '', '', 'Sales', 5)
('EE-016', 'Quentin', 'Paul', '', 'Male', '', 'Married', '5/18/2018', 'EE-017', '', '', 'Sales', 5)
('EE-017', 'Felicia', 'Kellogg', 'Paula', 'Female', '', 'Divorced', '5/19/2018', 'EE-001', '', '', 'Sales', 5)
('EE-018', 'Barbra', 'Banton', 'Betty', 'Female', '', 'Single', '5/20/2018', 'EE-017', '', '', 'Sales', 5)
('EE-019', 'Saul', 'Denosen', 'Peter', 'Male', '', 'Single', '5/21/2018', 'EE-017', '', '', 'Sales', 5)
('EE-020', 'Leon', 'Williams', '', 'Male', '', 'Single', '5/22/2018', 'EE-017', '', '', 'Sales', 5)
('EE-001', 'George', 'Deeds', 'Oscar', 'Male', '', 'Married', '2/12/2011', '', '', '', 'Finance', 5)
('EE-002', 'Mary', 'Wells', 'Virginia', 'Female', '', 'Married', '3/10/2015', 'EE-001', '5/12/2019', 'Quit', 'Finance', 5)
('EE-003', 'Donald', 'Wright', '', 'Male', '', 'Divorced', '8/1/2014', 'EE-001', '6/20/2020', 'Fired', 'Back Office', 5)
('EE-004', 'Shiela', 'Soros', 'Olivia', 'Female', '', 'Married', '2/12/2017', 'EE-007', '8/9/2020', 'Died', 'Accounting', 5)
('EE-005', 'Samuel', 'Rickets', 'Axel', 'Male', '', 'Single', '12/6/2017', 'EE-001', '', '', 'Finance', 5)
('EE-006', 'April', 'Walters', 'Amanda', 'Female', '', 'Married', '11/4/2015', 'EE-001', '', '', 'Finance', 5)
('EE-007', 'Avi', 'Feldman', '', 'Male', '', 'Single', '6/13/2016', 'EE-001', '', '', 'Accounting', 5)
('EE-008', 'Lea', 'Goldman', 'Elisa', 'Female', '', 'Single', '7/18/2019', 'EE-005', '', '', 'Finance', 5)
('EE-009', 'Henry', 'Williams', 'Robert', 'Male', '', 'Widowed', '10/5/2017', 'EE-005', '', '', 'Finance', 5)
('EE-010', 'Lois', 'Engels', '', 'Female', '', 'Single', '3/18/2010', 'EE-001', '', '', 'Human Resources', 5)
('EE-011', 'Fredrick', 'Rome', 'Aaron', 'Male', '', 'Single', '8/1/2018', 'EE-010', '', '', 'Human Resources', 5)
('EE-012', 'Regina', 'Polk', 'Ann', 'Female', '', 'Single', '12/10/2018', 'EE-010', '', '', 'Human Resources', 5)
('EE-013', 'Sara', 'Silver', 'Omara', 'Female', '', 'Single', '4/16/2016', 'EE-007', '', '', 'Accounting', 5)
('EE-014', 'Donald', 'Friar', 'Paul', 'Male', '', 'Single', '2/25/2017', 'EE-007', '', '', 'Accounting', 5)
('EE-015', 'Wendy', 'Rose', '', 'Female', '', 'Married', '5/17/2016', 'EE-017', '', '', 'Sales', 5)
('EE-016', 'Quentin', 'Paul', '', 'Male', '', 'Married', '5/18/2018', 'EE-017', '', '', 'Sales', 5)
('EE-017', 'Felicia', 'Kellogg', 'Paula', 'Female', '', 'Divorced', '5/19/2018', 'EE-001', '', '', 'Sales', 5)
('EE-018', 'Barbra', 'Banton', 'Betty', 'Female', '', 'Single', '5/20/2018', 'EE-017', '', '', 'Sales', 5)
('EE-019', 'Saul', 'Denosen', 'Peter', 'Male', '', 'Single', '5/21/2018', 'EE-017', '', '', 'Sales', 5)
('EE-020', 'Leon', 'Williams', '', 'Male', '', 'Single', '5/22/2018', 'EE-017', '', '', 'Sales', 5)