In [ ]:
import os
import mysql.connector


mysql_config =  {
  'user': 'root',
  'password': 'Admin321',
  'host': '127.0.0.1',
  'auth_plugin':'mysql_native_password'
}
conn = mysql.connector.connect(**mysql_config)
curr = conn.cursor(buffered=True)
curr.execute('CREATE DATABASE IF NOT EXISTS Country_info;')  # <------ The database
conn.commit()
curr.execute('USE Country_info;')
sql = '''CREATE TABLE IF NOT EXISTS population 
        (num INT,
        Country VARCHAR(10),  
        population INT, 
        migrants VARCHAR(10), 
        median_age INT);'''

curr.execute(sql)
conn.commit()
curr.execute('truncate table population;')
conn.commit()

In [ ]:
import os
import mysql.connector
# 
os.chdir(r'/Users/julis_478/Documents/Python Immersives/PY-112 SQL, No SQL/Classes/Day18')
mysql_config =  {
  'user': 'root',
  'password': 'Admin321',
  'host': '127.0.0.1',
  'auth_plugin':'mysql_native_password'
}
conn = mysql.connector.connect(**mysql_config)
curr = conn.cursor(buffered=True)
curr.execute('CREATE DATABASE IF NOT EXISTS Country_info2;')  # <------ The database
conn.commit()
curr.execute('USE Country_info2;')
sql = '''CREATE TABLE IF NOT EXISTS population 
        (num INT,
        Country VARCHAR(30),  
        population INT, 
        migrants INT, 
        median_age INT);'''

curr.execute(sql)
conn.commit()
curr.execute('truncate table population;')
conn.commit()

with open('World_country_populations.csv','r') as fh:
    headline = fh.readline()
    print (headline)
    rows = fh.readlines()
    for row in rows:
        # print (row)
        # print (row.strip())
        list_row = row.strip().replace('\n', '').split(',')
        # print (num, Country, population, migrants, median_age)
        num, Country, population, migrants, median_age = int(list_row[0]), list_row[1], int(list_row[2]), list_row[7], list_row[9]
        print (num, Country, population, migrants, median_age)
        if migrants:
            migrants = int(list_row[7])
        sql = f'''INSERT INTO population (num, Country, population, migrants, median_age) VALUES ({num},'{Country}',{population},{migrants},{median_age})'''
        #         sql = f'''INSERT INTO stock_price (symbol, trade_date, close_price, volume) 
        # # VALUES
        # # ('{symbol}','{date_op}','{close_value}','{volume}')
        # # '''
        curr.execute(sql)
        conn.commit()
        # print(sql)
conn.close()

# SQL

In [262]:
import sqlite3
import os

os.chdir(r'/Users/julis_478/Documents/Python Immersives/PY-112 SQL, No SQL/Classes/Day18')

conn = sqlite3.connect('Country_info.db')  # <== create the database
c = conn.cursor()
c.executescript('''CREATE TABLE IF NOT EXISTS population 
        (num INTEGER, 
        country TEXT, 
        population_c INTEGER, 
        migrants FLOAT, 
        median_age FLOAT);
        
        CREATE TABLE IF NOT EXISTS gdp_info 
        (territory TEXT, 
        Region TEXT, 
        Estimate FLOAT, 
        Year TEXT);
        ''')
conn.commit()
c.execute('DELETE FROM population')
conn.commit()

with open('World_country_populations.csv','r') as fh:
    headline = fh.readline()
    print (headline)
    rows = fh.readlines()
    # print (rows[0])
    for row in rows:
        list_row = row.strip().replace('\n', '').split(',')
        # print (list_row)
        if 'Ivoire' in list_row[1]:
                # print (list_row)  
                num, Country, population = int(list_row[0]), 'CÃ´te dIvoire', int(list_row[2])
        else:
                num, Country, population = int(list_row[0]), list_row[1].strip(), int(list_row[2])
        migrants = 0 if not list_row[7] or list_row[7] == 'N.A.' else float(list_row[7])
        median_age = 0 if not list_row[9] or list_row[9] == 'N.A.' or list_row[9] == 'N.A. ' else int(list_row[9])

        c.execute(f"""INSERT INTO population (num, country, population_c, migrants, median_age) VALUES ({num},'{Country}',{population},'{migrants}','{median_age}')""")
conn.commit() 

import os

os.chdir(r'/Users/julis_478/Documents/Python Immersives/PY-112 SQL, No SQL/Classes/Day18')

with open('GDP_countries.txt', 'r') as f:
    headline = f.readline()
    lines = f.readlines()
    print (headline)
    # print (lines)
    for row in lines:
   
        list_row = row.strip().replace('[n','').replace(']','').split('\t')
        list_row2 = list_row[0].strip(), list_row[1], list_row[2], list_row[3]
        c.execute(f"""INSERT INTO gdp_info (territory,Region, Estimate, Year) VALUES (?,?,?,?)""", list_row2)
        conn.commit()

        if list_row[5]:
            list_row2 = list_row[0], list_row[1], list_row[4], list_row[5]
            c.execute(f"""INSERT INTO gdp_info (territory,Region, Estimate, Year) VALUES (?,?,?,?)""", list_row2)
            conn.commit()
        
        try:
            if list_row[6] and list_row[7]: 
                list_row2 = list_row[0], list_row[1], list_row[6], list_row[7]
                c.execute(f"""INSERT INTO gdp_info (territory,Region, Estimate, Year) VALUES (?,?,?,?)""", list_row2)
                conn.commit()
        except:
            pass


conn.close()

num,Country,population,year_change,net_change,density,land_area_km2,migrants,fertility_rate,Median_age,Urban_pop_pct,World_share

CountriesCountry_Territory	Region	Estimate	Year	Estimate	Year	Estimate	Year

1 - Calculate the population range
2 - Which countries are in the bottom 20% of population
3 - What is the total population of the bottom 50% of countries
4 - What is the mean population
5 - Using the statistics library what is the standard deviation of the population data
6 - How many countries are within 1 standard deviation of the mean
7 - Display the country name, population , and GDP for 2021
8 - Print the top 10 countries GDP per population
9 - Print the bottom 50 countries GDP per population

In [288]:
import sqlite3
import os

os.chdir(r'/Users/julis_478/Documents/Python Immersives/PY-112 SQL, No SQL/Classes/Day18')

conn = sqlite3.connect('Country_info.db')  # <== create the database
c = conn.cursor()

# 1 - Calculate the population range
c.execute('SELECT MIN(population_c), MAX(population_c) FROM population')
rows = c.fetchall()
print(f'1 - Calculate the population range: ({rows[0][0]}, {rows[0][1]})')

# 2 - Which countries are in the bottom 20% of population
c.execute('SELECT COUNT(*)*.2 FROM population ORDER BY population_c ASC')
rows = c.fetchall()
c.execute(f'SELECT * FROM population ORDER BY population_c ASC LIMIT {round(rows[0][0])}')
rows = c.fetchall()
[print (f'{i}. {x[:3]}') for i,x in enumerate (rows)]

1 - Calculate the population range: (801, 1439323776)
0. (235, 'Holy See', 801)
1. (234, 'Tokelau', 1357)
2. (233, 'Niue', 1626)
3. (232, 'Falkland Islands', 3480)
4. (231, 'Montserrat', 4992)
5. (230, 'Saint Pierre & Miquelon', 5794)
6. (229, 'Saint Helena', 6077)
7. (228, 'Saint Barthelemy', 9877)
8. (227, 'Nauru', 10824)
9. (226, 'Wallis & Futuna', 11239)
10. (225, 'Tuvalu', 11792)
11. (224, 'Anguilla', 15003)
12. (223, 'Cook Islands', 17564)
13. (222, 'Palau', 18094)
14. (221, 'Caribbean Netherlands', 26223)
15. (220, 'British Virgin Islands', 30231)
16. (219, 'Gibraltar', 33691)
17. (218, 'San Marino', 33931)
18. (217, 'Liechtenstein', 38128)
19. (216, 'Saint Martin', 38666)
20. (215, 'Turks and Caicos', 38717)
21. (214, 'Monaco', 39242)
22. (213, 'Sint Maarten', 42876)
23. (212, 'Faeroe Islands', 48863)
24. (211, 'Saint Kitts & Nevis', 53199)
25. (210, 'American Samoa', 55191)
26. (209, 'Greenland', 56770)
27. (208, 'Northern Mariana Islands', 57559)
28. (207, 'Marshall Islands', 59190)
29. (206, 'Bermuda', 62278)
30. (205, 'Cayman Islands', 65722)
31. (204, 'Dominica', 71986)
32. (203, 'Andorra', 77265)
33. (202, 'Isle of Man', 85033)
34. (201, 'Antigua and Barbuda', 97929)
35. (200, 'Seychelles', 98347)
36. (199, 'U.S. Virgin Islands', 104425)
37. (198, 'Tonga', 105695)
38. (197, 'Aruba', 106766)
39. (196, 'St. Vincent & Grenadines', 110940)
40. (195, 'Grenada', 112523)
41. (194, 'Kiribati', 119449)
42. (193, 'CuraÃ§ao', 164093)
43. (192, 'Guam', 168775)
44. (191, 'Channel Islands', 173863)
45. (190, 'Saint Lucia', 183627)
46. (189, 'Samoa', 198414)

[None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None]

In [253]:
import sqlite3
import os

os.chdir(r'/Users/julis_478/Documents/Python Immersives/PY-112 SQL, No SQL/Classes/Day18')

conn = sqlite3.connect('Country_info.db')  # <== create the database
c = conn.cursor()

# 1 - Calculate the population range
c.execute('SELECT population_c FROM population ORDER BY population_c ASC')
rows = c.fetchall()
print(f'1 - Calculate the population range: ({rows[0][0]}, {rows[-1][0]})')

# 2 - Which countries are in the bottom 20% of population
max_pop = rows[-1][0]
twenty_pop = round((max_pop*20)/100)
c.execute(f'SELECT country FROM population WHERE population_c < {twenty_pop}')
rows = c.fetchall()
print('2 - Which countries are in the bottom 20% of population:')
for row in rows:
    print(f' - {row[0]}')

# 3 - What is the total population of the bottom 50% of countries
fifty_pop = round((max_pop*50)/100)
c.execute(f'SELECT population_c FROM population WHERE population_c < {fifty_pop}')
rows = c.fetchall()
fit_pop = [row[0] for row in rows]
print (f'3 - What is the total population of the bottom 50% of countries: {sum(fit_pop)}')

conn.close()

1 - Calculate the population range: (801, 1439323776)
2 - Which countries are in the bottom 20% of population:
 - Holy See
 - Tokelau
 - Niue
 - Falkland Islands
 - Montserrat
 - Saint Pierre & Miquelon
 - Saint Helena
 - Saint Barthelemy
 - Nauru
 - Wallis & Futuna
 - Tuvalu
 - Anguilla
 - Cook Islands
 - Palau
 - Caribbean Netherlands
 - British Virgin Islands
 - Gibraltar
 - San Marino
 - Liechtenstein
 - Saint Martin
 - Turks and Caicos
 - Monaco
 - Sint Maarten
 - Faeroe Islands
 - Saint Kitts & Nevis
 - American Samoa
 - Greenland
 - Northern Mariana Islands
 - Marshall Islands
 - Bermuda
 - Cayman Islands
 - Dominica
 - Andorra
 - Isle of Man
 - Antigua and Barbuda
 - Seychelles
 - U.S. Virgin Islands
 - Tonga
 - Aruba
 - St. Vincent & Grenadines
 - Grenada
 - Kiribati
 - CuraÃ§ao
 - Guam
 - Channel Islands
 - Saint Lucia
 - Samoa
 - Sao Tome & Principe
 - Mayotte
 - French Polynesia
 - New Caledonia
 - Barbados
 - French Guiana
 - Vanuatu
 - Iceland
 - Martinique
 - Bahamas
 - Belize
 - Guadeloupe
 - Brunei
 - Malta
 - Maldives
 - Micronesia
 - Cabo Verde
 - Suriname
 - Western Sahara
 - Luxembourg
 - Montenegro
 - Macao
 - Solomon Islands
 - Bhutan
 - Guyana
 - Comoros
 - RÃ©union
 - Fiji
 - Djibouti
 - Eswatini
 - Cyprus
 - Mauritius
 - Timor-Leste
 - Estonia
 - Trinidad and Tobago
 - Equatorial Guinea
 - Bahrain
 - Latvia
 - Guinea-Bissau
 - Slovenia
 - North Macedonia
 - Lesotho
 - Gabon
 - Botswana
 - Gambia
 - Namibia
 - Lithuania
 - Puerto Rico
 - Albania
 - Qatar
 - Jamaica
 - Armenia
 - Mongolia
 - Bosnia and Herzegovina
 - Uruguay
 - Eritrea
 - Georgia
 - Moldova
 - Croatia
 - Kuwait
 - Panama
 - Mauritania
 - New Zealand
 - Central African Republic
 - Ireland
 - Liberia
 - Costa Rica
 - State of Palestine
 - Oman
 - Norway
 - Slovakia
 - Congo
 - Finland
 - Denmark
 - Singapore
 - Turkmenistan
 - El Salvador
 - Kyrgyzstan
 - Nicaragua
 - Lebanon
 - Libya
 - Bulgaria
 - Paraguay
 - Laos
 - Hong Kong
 - Sierra Leone
 - Togo
 - Switzerland
 - Israel
 - Serbia
 - Papua New Guinea
 - Austria
 - Belarus
 - Tajikistan
 - Hungary
 - United Arab Emirates
 - Honduras
 - Sweden
 - Azerbaijan
 - Portugal
 - Jordan
 - Greece
 - Czech Republic (Czechia)
 - Dominican Republic
 - South Sudan
 - Cuba
 - Haiti
 - Belgium
 - Bolivia
 - Tunisia
 - Burundi
 - Benin
 - Rwanda
 - Guinea
 - Zimbabwe
 - Somalia
 - Chad
 - Cambodia
 - Senegal
 - Netherlands
 - Syria
 - Ecuador
 - Guatemala
 - Zambia
 - Kazakhstan
 - Chile
 - Malawi
 - Romania
 - Mali
 - Burkina Faso
 - Sri Lanka
 - Taiwan
 - Niger
 - Australia
 - North Korea
 - CÃ´te dIvoire
 - Cameroon
 - Madagascar
 - Venezuela
 - Nepal
 - Yemen
 - Ghana
 - Mozambique
 - Malaysia
 - Angola
 - Peru
 - Uzbekistan
 - Saudi Arabia
 - Morocco
 - Canada
 - Poland
 - Afghanistan
 - Iraq
 - Ukraine
 - Sudan
 - Algeria
 - Argentina
 - Uganda
 - Spain
 - Colombia
 - South Korea
 - Kenya
 - Myanmar
 - South Africa
 - Tanzania
 - Italy
 - France
 - United Kingdom
 - Thailand
 - Germany
 - Iran
 - Turkey
 - DR Congo
 - Vietnam
 - Egypt
 - Philippines
 - Ethiopia
 - Japan
 - Mexico
 - Russia
 - Bangladesh
 - Nigeria
 - Brazil
 - Pakistan
 - Indonesia
3 - What is the total population of the bottom 50% of countries: 4975904469

In [255]:
import statistics
c.execute(f'SELECT population_c FROM population')
rows = c.fetchall()

# 4 - What is the mean population
c.execute(f'SELECT sum(population_c)/count(*) FROM population')
rows = c.fetchall()
mean_p = rows[0][0]
print (f'4 - What is the mean population {mean_p}')

4 - What is the mean population 33171202

In [258]:
# 5 - Using the statistics library what is the standard deviation of the population data
import statistics
c.execute(f'SELECT population_c FROM population')
rows = c.fetchall()
pop = [row[0] for row in rows]
std_derv = round(statistics.stdev(pop),2)
print (f'5 - What is the standard deviation of the population data: {std_derv}')

# 6 - How many countries are within 1 standard deviation of the mean
c.execute(f'SELECT country FROM population WHERE population_c > {mean_p} AND population_c < {mean_p + std_derv}')
rows = c.fetchall()
count_pop = [row[0] for row in rows]
print (f'6 - How many countries are within 1 standard deviation of the mean: {len(count_pop)}')

conn.close()

5 - What is the standard deviation of the population data: 135136985.28
6 - How many countries are within 1 standard deviation of the mean: 35

In [259]:
import sqlite3
import os

os.chdir(r'/Users/julis_478/Documents/Python Immersives/PY-112 SQL, No SQL/Classes/Day18')

conn = sqlite3.connect('Country_info.db')  # <== create the database
c = conn.cursor()

# 7 - Display the country name, population , and GDP for 2021
c.execute(f'SELECT A.country, A.population_c, B.Estimate FROM population A LEFT JOIN gdp_info B on A.country = B.territory WHERE B.Year == "2021" ORDER BY A.population_c DESC')
rows = c.fetchall()
print ('7 - Display the country name, population, and GDP for 2021: ')
[print (f' - {row}') for row in rows]

7 - Display the country name, population, and GDP for 2021:
 - ('India', 1380004385, '3,049,704')
 - ('United States', 331002651, ' 22,675,271')
 - ('Indonesia', 273523615, '1,158,783')
 - ('Pakistan', 220892340, '286,340')
 - ('Brazil', 212559417, '1,491,772')
 - ('Nigeria', 206139589, '514,049')
 - ('Russia', 145934462, '1,710,734')
 - ('Mexico', 128932753, '1,192,480')
 - ('Japan', 126476461, '5,378,136')
 - ('Ethiopia', 114963588, '93,966')
 - ('Philippines', 109581078, '402,638')
 - ('Egypt', 102334404, '394,284')
 - ('Vietnam', 97338579, '354,868')
 - ('DR Congo', 89561403, '55,088')
 - ('Turkey', 84339067, '794,530')
 - ('Iran', 83992949, '682,859')
 - ('Germany', 83783942, '4,319,286')
 - ('Thailand', 69799978, '538,735')
 - ('United Kingdom', 67886011, '3,124,650')
 - ('France', 65273511, '2,938,271')
 - ('Italy', 60461826, '2,106,287')
 - ('Tanzania', 59734218, '65,919')
 - ('South Africa', 59308690, '329,529')
 - ('Myanmar', 54409800, '76,195')
 - ('Kenya', 53771296, '106,041')
 - ('South Korea', 51269185, '1,806,707')
 - ('Colombia', 50882891, '295,610')
 - ('Spain', 46754778, '1,461,552')
 - ('Uganda', 45741007, '41,271')
 - ('Argentina', 45195774, '418,150')
 - ('Algeria', 43851044, '151,459')
 - ('Sudan', 43849260, '35,827')
 - ('Iraq', 40222493, '190,733')
 - ('Afghanistan', 38928346, '19,938')
 - ('Poland', 37846611, '642,121')
 - ('Canada', 37742154, '1,883,487')
 - ('Morocco', 36910560, '124,003')
 - ('Saudi Arabia', 34813871, '804,921')
 - ('Uzbekistan', 33469203, '61,203')
 - ('Peru', 32971854, '225,918')
 - ('Angola', 32866272, '66,493')
 - ('Malaysia', 32365999, '387,093')
 - ('Mozambique', 31255435, '13,957')
 - ('Ghana', 31072940, '74,260')
 - ('Yemen', 29825964, '25,095')
 - ('Nepal', 29136808, '36,084')
 - ('Venezuela', 28435940, '42,530')
 - ('Madagascar', 27691018, '14,746')
 - ('Cameroon', 26545863, '44,893')
 - ('Australia', 25499884, '1,617,543')
 - ('Niger', 24206644, '15,899')
 - ('Sri Lanka', 21413249, '84,532')
 - ('Burkina Faso', 20903273, '18,853')
 - ('Mali', 20250833, '19,912')
 - ('Romania', 19237691, '289,130')
 - ('Malawi', 19129952, '9,268')
 - ('Chile', 19116201, '307,938')
 - ('Kazakhstan', 18776707, '187,836')
 - ('Zambia', 18383955, '18,955')
 - ('Guatemala', 17915568, '81,402')
 - ('Ecuador', 17643054, '100,595')
 - ('Netherlands', 17134872, '1,012,598')
 - ('Senegal', 16743927, '27,927')
 - ('Cambodia', 16718965, '27,239')
 - ('Chad', 16425864, '12,531')
 - ('Somalia', 15893222, '5,367')
 - ('Zimbabwe', 14862924, '26,085')
 - ('Guinea', 13132795, '16,339')
 - ('Rwanda', 12952218, '10,633')
 - ('Benin', 12123200, '17,327')
 - ('Burundi', 11890784, '3,244')
 - ('Tunisia', 11818619, '44,265')
 - ('Bolivia', 11673021, '43,110')
 - ('Belgium', 11589623, '578,996')
 - ('Haiti', 11402528, '22,431')
 - ('South Sudan', 11193725, '4,461')
 - ('Dominican Republic', 10847910, '83,917')
 - ('Greece', 10423054, '209,857')
 - ('Jordan', 10203134, '44,979')
 - ('Portugal', 10196709, '257,391')
 - ('Azerbaijan', 10139177, '49,914')
 - ('Sweden', 10099265, '625,948')
 - ('Honduras', 9904607, '26,161')
 - ('United Arab Emirates', 9890402, '401,513')
 - ('Hungary', 9660351, '176,543')
 - ('Tajikistan', 9537645, '7,825')
 - ('Belarus', 9449323, '60,725')
 - ('Austria', 9006398, '481,796')
 - ('Papua New Guinea', 8947024, '24,536')
 - ('Serbia', 8737371, '60,435')
 - ('Israel', 8655535, '446,708')
 - ('Switzerland', 8654622, '824,734')
 - ('Togo', 8278724, '8,627')
 - ('Sierra Leone', 7976983, '4,420')
 - ('Laos', 7275560, '20,440')
 - ('Paraguay', 7132538, '37,836')
 - ('Bulgaria', 6948445, '77,782')
 - ('Libya', 6871292, '24,267')
 - ('Nicaragua', 6624554, '12,283')
 - ('Kyrgyzstan', 6524195, '7,470')
 - ('El Salvador', 6486205, '26,277')
 - ('Turkmenistan', 6031200, '54,218')
 - ('Singapore', 5850342, '374,394')
 - ('Denmark', 5792202, '392,570')
 - ('Finland', 5540720, '300,484')
 - ('Congo', 5518087, '12,022')
 - ('Slovakia', 5459642, '117,664')
 - ('Norway', 5421241, '444,519')
 - ('Oman', 5106626, '74,115')
 - ('Costa Rica', 5094118, '61,178')
 - ('Liberia', 5057681, '3,370')
 - ('Ireland', 4937786, '476,663')
 - ('Central African Republic', 4829767, '2,718')
 - ('New Zealand', 4822233, '243,332')
 - ('Mauritania', 4649658, '9,239')
 - ('Panama', 4314767, '59,377')
 - ('Kuwait', 4270571, '126,930')
 - ('Croatia', 4105267, '65,217')
 - ('Georgia', 3989167, '16,163')
 - ('Eritrea', 3546421, '2,250')
 - ('Uruguay', 3473730, '55,459')
 - ('Bosnia and Herzegovina', 3280819, '21,953')
 - ('Mongolia', 3278290, '14,233')
 - ('Armenia', 2963243, '12,251')
 - ('Jamaica', 2961167, '14,600')
 - ('Qatar', 2881053, '166,031')
 - ('Albania', 2877797, '17,138')
 - ('Puerto Rico', 2860853, '100,684')
 - ('Lithuania', 2722289, '62,198')
 - ('Namibia', 2540905, '11,381')
 - ('Gambia', 2416668, '2,078')
 - ('Botswana', 2351627, '18,726')
 - ('Gabon', 2225734, '18,362')
 - ('Lesotho', 2142249, '2,458')
 - ('North Macedonia', 2083374, '13,821')
 - ('Slovenia', 2078938, '59,132')
 - ('Guinea-Bissau', 1968001, '1,647')
 - ('Latvia', 1886198, '37,720')
 - ('Bahrain', 1701575, '37,503')
 - ('Equatorial Guinea', 1402985, '11,726')
 - ('Trinidad and Tobago', 1399488, '22,161')
 - ('Estonia', 1326535, '35,187')
 - ('Mauritius', 1271768, '12,212')
 - ('Cyprus', 1207359, '26,479')
 - ('Eswatini', 1160164, '4,226')
 - ('Djibouti', 988000, '3,663')
 - ('Fiji', 896445, '4,586')
 - ('Comoros', 869601, '1,309')
 - ('Guyana', 786552, '7,255')
 - ('Bhutan', 771608, '2,480')
 - ('Solomon Islands', 686884, '1,644')
 - ('Montenegro', 628066, '5,651')
 - ('Luxembourg', 625978, '84,077')
 - ('Suriname', 586632, '2,465')
 - ('Micronesia', 548914, 401.0)
 - ('Maldives', 540544, '4,536')
 - ('Malta', 441543, '16,476')
 - ('Brunei', 437479, '15,278')
 - ('Belize', 397628, '1,700')
 - ('Bahamas', 393244, '11,706')
 - ('Iceland', 341243, '24,155')
 - ('Vanuatu', 307145, 912.0)
 - ('Barbados', 287375, '4,628')
 - ('Samoa', 198414, 752.0)
 - ('Saint Lucia', 183627, '1,787')
 - ('Kiribati', 119449, 231.0)
 - ('Grenada', 112523, '1,041')
 - ('Aruba', 106766, '2,582')
 - ('Tonga', 105695, 508.0)
 - ('Seychelles', 98347, 948.0)
 - ('Antigua and Barbuda', 97929, '1,376')
 - ('Dominica', 71986, 523.0)
 - ('Marshall Islands', 59190, 234.0)
 - ('San Marino', 33931, '1,688')
 - ('Palau', 18094, 229.0)
 - ('Tuvalu', 11792, 57.0)
 - ('Nauru', 10824, 133.0)
[('India', 1380004385, '3,049,704'), ('United States', 331002651, ' 22,675,271'), ('Indonesia', 273523615, '1,158,783'), ('Pakistan', 220892340, '286,340'), ('Brazil', 212559417, '1,491,772'), ('Nigeria', 206139589, '514,049'), ('Russia', 145934462, '1,710,734'), ('Mexico', 128932753, '1,192,480'), ('Japan', 126476461, '5,378,136'), ('Ethiopia', 114963588, '93,966'), ('Philippines', 109581078, '402,638')]

In [261]:
# 8 - Print the top 10 countries GDP per population
c.execute(f'SELECT B.Estimate/A.population_c, A.country FROM population A LEFT JOIN gdp_info B on A.country = B.territory ORDER BY B.Estimate/A.population_c DESC')
rows = c.fetchall()
print ('8 - Print the top 10 countries GDP per population:')
for i in rows[:11]:
    print (f' - {i}')
print ()


# 9 - Print the bottom 50 countries GDP per population
print (f'9 - Print the bottom 50 countries GDP per population:')
for i in rows[-50:]:
    print (f' - {i}')
conn.close()

8 - Print the top 10 countries GDP per population:
 - (0.40444711538461536, 'Montserrat')
 - (0.13457308538292342, 'Anguilla')
 - (0.11495103621043043, 'Cook Islands')
 - (0.06678574972710132, 'British Virgin Islands')
 - (0.05295321023919429, 'Liechtenstein')
 - (0.051449977065389126, 'Monaco')
 - (0.047089280716484744, 'Sint Maarten')
 - (0.03556455874581645, 'Greenland')
 - (0.0324191528308552, 'Bermuda')
 - (0.030720306746599313, 'Cayman Islands')
 - (0.026130848378955542, 'Andorra')

9 - Print the bottom 50 countries GDP per population:
 - (0, 'Brazil')
 - (0, 'Pakistan')
 - (0, 'Pakistan')
 - (0, 'Pakistan')
 - (0, 'Indonesia')
 - (0, 'Indonesia')
 - (0, 'Indonesia')
 - (0, 'United States')
 - (0, 'United States')
 - (0, 'United States')
 - (0, 'India')
 - (0, 'India')
 - (0, 'India')
 - (0, 'China')
 - (0, 'China')
 - (0, 'China')
 - (None, 'Holy See')
 - (None, 'Tokelau')
 - (None, 'Niue')
 - (None, 'Falkland Islands')
 - (None, 'Saint Pierre & Miquelon')
 - (None, 'Saint Helena')
 - (None, 'Saint Barthelemy')
 - (None, 'Wallis & Futuna')
 - (None, 'Caribbean Netherlands')
 - (None, 'Gibraltar')
 - (None, 'Saint Martin')
 - (None, 'Turks and Caicos')
 - (None, 'Faeroe Islands')
 - (None, 'Saint Kitts & Nevis')
 - (None, 'American Samoa')
 - (None, 'Northern Mariana Islands')
 - (None, 'Isle of Man')
 - (None, 'U.S. Virgin Islands')
 - (None, 'St. Vincent & Grenadines')
 - (None, 'Guam')
 - (None, 'Channel Islands')
 - (None, 'Sao Tome & Principe')
 - (None, 'Mayotte')
 - (None, 'French Guiana')
 - (None, 'Martinique')
 - (None, 'Guadeloupe')
 - (None, 'Cabo Verde')
 - (None, 'Western Sahara')
 - (None, 'Macao')
 - (None, 'RÃ©union')
 - (None, 'Timor-Leste')
 - (None, 'State of Palestine')
 - (None, 'Czech Republic (Czechia)')
 - (None, 'CÃ´te dIvoire')

In [230]:
c.execute(f'SELECT A.country, A.population_c, B.Estimate FROM population A LEFT JOIN gdp_info B on A.country = B.territory WHERE B.Year == "2021" ORDER BY A.population_c DESC')
rows = c.fetchall()
# [print (f'7 - Display the country name, population , and GDP for 2021: {row}') for row in rows]


# 8 - Print the top 10 countries GDP per population
print (rows[:11])

[('India', 1380004385, '3,049,704'), ('United States', 331002651, ' 22,675,271'), ('Indonesia', 273523615, '1,158,783'), ('Pakistan', 220892340, '286,340'), ('Brazil', 212559417, '1,491,772'), ('Nigeria', 206139589, '514,049'), ('Russia', 145934462, '1,710,734'), ('Mexico', 128932753, '1,192,480'), ('Japan', 126476461, '5,378,136'), ('Ethiopia', 114963588, '93,966'), ('Philippines', 109581078, '402,638')]